### ISSUE TITLE
Error when trying to start the Bot

### ISSUE THREAD

**Issue by EinsKatze** [KortaPo/DisnakeWavelinkBot#1]
Hey, when trying to start the Bot, I get the following error.
If u need any more Information on the Issue, please tell me, so I can try to provide them.

```C:\Users\User\Downloads\DisnakeWavelinkBot-master>python main.py
Traceback (most recent call last):
  File "C:\Users\User\Downloads\DisnakeWavelinkBot-master\main.py", line 3, in <module>
    from MusicBot import Bot
  File "C:\Users\User\Downloads\DisnakeWavelinkBot-master\MusicBot.py", line 15, in <module>
    data = json.load(f)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Program Files\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 67: character maps to <undefined>```

**Comment by KortaPo** [comment]
> Hey, when trying to start the Bot, I get the following error. If u need any more Information on the Issue, please tell me, so I can try to provide them.
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\User\Downloads\DisnakeWavelinkBot-master\main.py", line 3, in <module>
>     from MusicBot import Bot
>   File "C:\Users\User\Downloads\DisnakeWavelinkBot-master\MusicBot.py", line 15, in <module>
>     data = json.load(f)
>   File "C:\Program Files\Python310\lib\json\__init__.py", line 293, in load
>     return loads(fp.read(),
>   File "C:\Program Files\Python310\lib\encodings\cp1252.py", line 23, in decode
>     return codecs.charmap_decode(input,self.errors,decoding_table)[0]
> UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 67: character maps to <undefined>```
> ```
Is this generated while running from windows terminal / command prompt.?

**Comment by EinsKatze** [comment]
> 
> Is this generated while running from windows terminal / command prompt.?

Yes it is.
Using the Windows Terminal from Windows 11 Version 21H2.

**Comment by KortaPo** [comment]
It was an issue because of different file formatting, and hopefully this commit should fix that issue. Thank you for reporting.

**Comment by EinsKatze** [comment]
Yes that fixed *this* bug.
