### ISSUE TITLE
Error when trying to use the play command.

### ISSUE THREAD

**Issue by EinsKatze** [KortaPo/DisnakeWavelinkBot#2]
Hey, its me again. c:
When trying to use the play command the following error gets generated.

`An error has occurred while executing play command. The error has been generated on mystbin. Please report this to EinsKatze#0546`
With the following "View Error" Link.
https://mystb.in/SharesIncreasinglyEco.py

Running the Bot via Windows Terminal, Win 11 21H2.
If u need any further Information feel free to ask me on Discord (or reply here and wait a bit hehe).

**Comment by KortaPo** [comment]
That error is raised by wavelink, basically if the wavelink tries to make some operations on the node and there aren't any nodes connected.
It could raise if the Lavalink hasn't started.

**Comment by EinsKatze** [comment]
Okay.
Later i will look if there was any error before, that could be the reason why that happened.

If i know more, i will write a new comment here.

**Comment by KortaPo** [comment]
Alright, also when the bot starts, it logs everything in the console about what happens, for eg, loading cogs, starting the Lavalink server etc etc. Also, you can send me hit me up on discord, KortaPo#8459.

**Comment by EinsKatze** [comment]
This is the first error popping up when starting the Bot. (The bot still starts tho)
Could this error be related to Windows/Antivirus Firewall?

```
Exception in thread Thread-1 (run_lavalink_process):
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\pascr\Downloads\DisnakeWavelinkBot-master\bot_utils\Lavalink_run.py", line 20, in run_lavalink_process
    process = subprocess.run(["which", program], capture_output=True, text=True)
  File "C:\Program Files\Python310\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
```


When the Bot tries to connect, another error pops up. Which makes sense ig.
https://ghostbin.com/h0ui2

**Comment by EinsKatze** [comment]
Didnt had Lavalink installed. KortaPo helped me via DC.
